apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-node-app-deployment
  labels:
    app: argo-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-node-app
  template:
    metadata:
      labels:
        app: argo-node-app 
    spec:
      containers:
      - name: argo-node-app
        image: https://aws_account_id.dkr.ecr.region.amazonaws.com/argoCDApp:v1
        ports:
        - containerPort: 3000



