apiVersion: v1
kind: Service
metadata:
  name: argo-node-app-service
spec:
  selector:
    app: argo-node-app 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
